import { readdir, access, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Generates src/manifest.gen.ts - static imports of every feature - because
 * the Lambda bundle cannot dynamic-import .ts files at runtime the way the
 * local dev server does. Local dev keeps live discovery; the deployed
 * artifact gets deterministic imports and a faster cold start.
 *
 * The manifest is gitignored ON PURPOSE: checking it in would recreate the
 * shared-file merge conflict the features/ directory design exists to avoid.
 * It is regenerated by `npm run gen` (part of gate and build).
 */

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

export async function listFeatureDirs(featuresDir: string): Promise<string[]> {
  const entries = await readdir(featuresDir, { withFileTypes: true });
  const dirs: string[] = [];
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    if (e.name.startsWith("_") || e.name.startsWith(".")) continue;
    try {
      await access(join(featuresDir, e.name, "feature.ts"));
      dirs.push(e.name);
    } catch {
      // No feature.ts - runtime discovery reports this; the manifest skips it.
    }
  }
  return dirs.sort((a, b) => a.localeCompare(b));
}

export function renderManifest(dirs: string[]): string {
  const imports = dirs
    .map((d, i) => `import f${i} from "../features/${d}/feature.ts";`)
    .join("\n");
  const list = dirs.map((_, i) => `f${i}`).join(", ");
  return `// AUTO-GENERATED by scripts/gen-manifest.ts - do not edit, do not commit.
import type { Feature } from "./spine/types.ts";
${imports}

export const features: Feature[] = [${list}];
`;
}

// Run directly: write the manifest.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const dirs = await listFeatureDirs(join(ROOT, "features"));
  await writeFile(join(ROOT, "src", "manifest.gen.ts"), renderManifest(dirs));
  console.log(`[gen] src/manifest.gen.ts: ${dirs.length} feature(s): ${dirs.join(", ")}`);
}
